version: '3'

services:

  mysql:

    image: mariadb

    volumes:

        - /data/mysql:/var/lib/mysql

    environment:

      MYSQL_ROOT_PASSWORD: Str0ngP@ss

      MYSQL_DATABASE: wordpress

      MYSQL_USER: wpuser

      MYSQL_PASSWORD: VeryStr0ngP@ss

    restart: always

  wordpress:

    image: wordpress:php7.3-fpm-alpine

    volumes:

      - /data/html:/var/www/html

    depends_on:

      - mysql

    environment:

      WORDPRESS_DB_HOST: mysql

      MYSQL_ROOT_PASSWORD: Str0ngP@ss

      WORDPRESS_DB_NAME: wordpress

      WORDPRESS_DB_USER: wpuser

      WORDPRESS_DB_PASSWORD: VeryStr0ngP@ss

      WORPDRESS_TABLE_PREFIX: wp_

    links:

      - mysql

    restart: always

  nginx:

    image: nginx:alpine

    volumes: 

     - /data/nginx:/etc/nginx/conf.d

     - /data/html:/var/www/html 

    ports: 

      - 8080:80

    links:

      - wordpress
